### ISSUE TITLE
すべてのフォームで右上の閉じるボタンを押すとエラーが起きる

### ISSUE THREAD

**Issue by popkechupki** [itsu020402/NukkitFormAPI#1]
```[CRITICAL] "'NukkitFormAPI v1.0.0'に'cn.nukkit.event.server.DataPacketReceiveEvent'Eventを渡すことができません でした: itsu.mcbe.form.event.NukkitFormEventListenerでのnull"
20:53:37 [ALERT] cn.nukkit.utils.EventException
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34)
        at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56)
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:553)
        at cn.nukkit.Player.handleDataPacket(Player.java:2032)
        at java.util.ArrayList.forEach(Unknown Source)
        at cn.nukkit.network.Network.processPackets(Network.java:178)
        at cn.nukkit.network.Network.processBatch(Network.java:160)
        at cn.nukkit.Player.handleDataPacket(Player.java:2038)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66)
        at cn.nukkit.network.Network.processInterfaces(Network.java:76)
        at cn.nukkit.Server.tick(Server.java:1068)
        at cn.nukkit.Server.tickProcessor(Server.java:842)
        at cn.nukkit.Server.start(Server.java:819)
        at cn.nukkit.Server.<init>(Server.java:502)
        at cn.nukkit.Nukkit.main(Nukkit.java:102)
Caused by: java.lang.NumberFormatException: For input string: ""
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at itsu.mcbe.form.event.NukkitFormEventListener.onReceive(NukkitFormEventListener.java:31)
        at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29)
        ... 16 more

**Comment by itsu020402** [comment]
ありがとうございます。
こちらでも把握していたバグです。

**Comment by itsu020402** [comment]
修正しました。
